### ISSUE TITLE
Can use ParadoxIp in a Windows Phone 8.1

### ISSUE THREAD

**Issue by saramgsilva** [tracstarr/ParadoxAlarmControl#11]
Hello,

I found this project I have few doubts:
- To use ParadoxIp in a WP app, I need to port it to a WP Class Library, right? And it is possible, everything is compatible? I think I found WebDriver as an incompatible reference.
- Can I run ParadoxIp in a project based in services deployed for a Azure Website? I found this error

![2015-09-29_21-48-38](https://cloud.githubusercontent.com/assets/2135829/10178000/1d6c56be-66f5-11e5-8f0e-ff85cc2e7fdd.jpg)

when I created a console application for test few things.

There is any solution for Windows Phone? 
There is more details about each project?

Thanks
Sara Silva

**Comment by tracstarr** [comment]
Hey Sara, sorry I didn't see this earlier. I doubt you'll be able to use directly on WP as you currently require phantomJS headless browser. I also suspect this is why you cannot run in azure website. You will need a small linux server which you then run on (or windows server) and connect your windows phone application to it using the web services.
