### ISSUE TITLE
Compiling on Debian fails

### ISSUE THREAD

**Issue by Rtaxerxes** [tracstarr/ParadoxAlarmControl#13]
I've installed PhantomJS 1.9 and Selenium via pip.

When I try to compile on Linux via Mono, I get the following output. I'm not sure if it is not finding Selenium or if it is a version problem.

root@bananapi:/opt/paradoxapi/ParadoxAlarmControl-master# xbuild ParadoxIp.sln 
XBuild Engine Version 12.0
Mono, Version 4.2.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 2/16/2016 8:54:09 PM.

---

Project "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp.sln" (default target(s)):
    Target ValidateSolutionConfiguration:
        Building solution configuration "Debug|Any CPU".
    Target Build:
        Project "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp/ParadoxIp.csproj" (default target(s)):
            Target RestorePackages:
                Executing: mono --runtime=v4.0.30319 "/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.exe" install "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp/packages.config" -source ""   -RequireConsent -solutionDir "/opt/paradoxapi/ParadoxAlarmControl-master/"
                Restoring NuGet packages...
                To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
                WARNING: Error: SendFailure (Error writing headers)
                Unable to find version '2.51.0' of package 'Selenium.Support'.
/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 "/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.exe" install "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp/packages.config" -source ""   -RequireConsent -solutionDir "/opt/paradoxapi/ParadoxAlarmControl-master/"' exited with code: 1.
            Task "Exec" execution -- FAILED
            Done building target "RestorePackages" in project "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp/ParadoxIp.csproj".-- FAILED
        Done building project "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp/ParadoxIp.csproj".-- FAILED
        Project "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel/Paradox.WebServices.ServiceModel.csproj" (default target(s)):
            Target RestorePackages:
                Executing: mono --runtime=v4.0.30319 "/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.exe" install "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel/packages.config" -source ""   -RequireConsent -solutionDir "/opt/paradoxapi/ParadoxAlarmControl-master/"
                Restoring NuGet packages...
                To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
                WARNING: Error: SendFailure (Error writing headers)
                Unable to find version '4.0.52' of package 'ServiceStack.Common'.
/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 "/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.exe" install "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel/packages.config" -source ""   -RequireConsent -solutionDir "/opt/paradoxapi/ParadoxAlarmControl-master/"' exited with code: 1.
            Task "Exec" execution -- FAILED
            Done building target "RestorePackages" in project "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel/Paradox.WebServices.ServiceModel.csproj".-- FAILED
        Done building project "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel/Paradox.WebServices.ServiceModel.csproj".-- FAILED
        Project "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/Paradox.WebServices.ServiceModel.SmartThings.csproj" (default target(s)):
/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/Paradox.WebServices.ServiceModel.SmartThings.csproj:  warning : Project has unknown ToolsVersion '14.0'. Using the default tools version '4.0' instead.
            Target PrepareForBuild:
                Configuration: Debug Platform: AnyCPU
            Target ResolveAssemblyReferences:
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'ServiceStack.Common, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL' not resolved
                For searchpath {CandidateAssemblyFiles}
                Warning: {CandidateAssemblyFiles} not supported currently
                For searchpath {HintPathFromItem}
                Considered ../packages/ServiceStack.Common.4.0.52/lib/net40/ServiceStack.Common.dll, but it does not exist.
                For searchpath {TargetFrameworkDirectory}
                Considered target framework dir /usr/lib/mono/4.5, assembly named 'ServiceStack.Common' not found.
                Considered target framework dir /usr/lib/mono/4.5/Facades/, assembly named 'ServiceStack.Common' not found.
                For searchpath {PkgConfig}
                Considered ServiceStack.Common, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL, but could not find in any pkg-config files.
                For searchpath {GAC}
                Considered ServiceStack.Common, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL, but could not find in the GAC.
                For searchpath {RawFileName}
                Considered 'ServiceStack.Common, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL' as a file, but the file does not exist
                For searchpath bin/Debug/
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Common' as a file, but the file does not exist
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Common.exe' as a file, but the file does not exist
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Common.dll' as a file, but the file does not exist
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'ServiceStack.Interfaces, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL' not resolved
                For searchpath {CandidateAssemblyFiles}
                Warning: {CandidateAssemblyFiles} not supported currently
                For searchpath {HintPathFromItem}
                Considered ../packages/ServiceStack.Interfaces.4.0.52/lib/portable-wp80+sl5+net40+win8+monotouch+monoandroid+xamarin.ios10/ServiceStack.Interfaces.dll, but it does not exist.
                For searchpath {TargetFrameworkDirectory}
                Considered target framework dir /usr/lib/mono/4.5, assembly named 'ServiceStack.Interfaces' not found.
                Considered target framework dir /usr/lib/mono/4.5/Facades/, assembly named 'ServiceStack.Interfaces' not found.
                For searchpath {PkgConfig}
                Considered ServiceStack.Interfaces, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL, but could not find in any pkg-config files.
                For searchpath {GAC}
                Considered ServiceStack.Interfaces, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL, but could not find in the GAC.
                For searchpath {RawFileName}
                Considered 'ServiceStack.Interfaces, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL' as a file, but the file does not exist
                For searchpath bin/Debug/
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Interfaces' as a file, but the file does not exist
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Interfaces.exe' as a file, but the file does not exist
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Interfaces.dll' as a file, but the file does not exist
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'ServiceStack.Text, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL' not resolved
                For searchpath {CandidateAssemblyFiles}
                Warning: {CandidateAssemblyFiles} not supported currently
                For searchpath {HintPathFromItem}
                Considered ../packages/ServiceStack.Text.4.0.52/lib/net40/ServiceStack.Text.dll, but it does not exist.
                For searchpath {TargetFrameworkDirectory}
                Considered target framework dir /usr/lib/mono/4.5, assembly named 'ServiceStack.Text' not found.
                Considered target framework dir /usr/lib/mono/4.5/Facades/, assembly named 'ServiceStack.Text' not found.
                For searchpath {PkgConfig}
                Considered ServiceStack.Text, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL, but could not find in any pkg-config files.
                For searchpath {GAC}
                Considered ServiceStack.Text, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL, but could not find in the GAC.
                For searchpath {RawFileName}
                Considered 'ServiceStack.Text, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL' as a file, but the file does not exist
                For searchpath bin/Debug/
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Text' as a file, but the file does not exist
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Text.exe' as a file, but the file does not exist
                Considered '/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/bin/Debug/ServiceStack.Text.dll' as a file, but the file does not exist
            Target GenerateSatelliteAssemblies:
            No input files were specified for target GenerateSatelliteAssemblies, skipping.
            Target GenerateTargetFrameworkMonikerAttribute:
            Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
            Target CoreCompile:
                Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/Paradox.WebServices.ServiceModel.SmartThings.dll Properties/AssemblyInfo.cs Request/SmartThingsSettingsRequest.cs Request/SmartThingsSettingsResetRequest.cs Request/SmartThingsStatusRequest.cs Request/StatusRequest.cs Response/SmartThingsStatusResponse.cs Response/StatusResponse.cs /target:library /define:"DEBUG;TRACE" /nostdlib /reference:/usr/lib/mono/4.5/System.dll /reference:/usr/lib/mono/4.5/System.Xml.Linq.dll /reference:/usr/lib/mono/4.5/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/4.5/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.5/System.Data.dll /reference:/usr/lib/mono/4.5/System.Net.Http.dll /reference:/usr/lib/mono/4.5/System.Xml.dll /reference:/usr/lib/mono/4.5/System.Core.dll /reference:/usr/lib/mono/4.5/mscorlib.dll /warn:4
Request/SmartThingsSettingsRequest.cs(1,7): error CS0246: The type or namespace name `ServiceStack' could not be found. Are you missing an assembly reference?
Request/SmartThingsSettingsResetRequest.cs(1,7): error CS0246: The type or namespace name`ServiceStack' could not be found. Are you missing an assembly reference?
Request/SmartThingsStatusRequest.cs(2,7): error CS0246: The type or namespace name `ServiceStack' could not be found. Are you missing an assembly reference?
Request/StatusRequest.cs(2,7): error CS0246: The type or namespace name`ServiceStack' could not be found. Are you missing an assembly reference?
Request/SmartThingsStatusRequest.cs(8,45): error CS0246: The type or namespace name `IReturn' could not be found. Are you missing an assembly reference?
Request/StatusRequest.cs(8,34): error CS0246: The type or namespace name`IReturn' could not be found. Are you missing an assembly reference?
            Task "Csc" execution -- FAILED
            Done building target "CoreCompile" in project "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/Paradox.WebServices.ServiceModel.SmartThings.csproj".-- FAILED
        Done building project "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/Paradox.WebServices.ServiceModel.SmartThings.csproj".-- FAILED
    Task "MSBuild" execution -- FAILED
    Done building target "Build" in project "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp.sln".-- FAILED
Done building project "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp.sln".-- FAILED

Build FAILED.

Warnings:

/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp.sln (default targets) ->
(Build target) ->
/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/Paradox.WebServices.ServiceModel.SmartThings.csproj (default targets) ->

```
/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/Paradox.WebServices.ServiceModel.SmartThings.csproj:  warning : Project has unknown ToolsVersion '14.0'. Using the default tools version '4.0' instead.
```

/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp.sln (default targets) ->
(Build target) ->
/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/Paradox.WebServices.ServiceModel.SmartThings.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

```
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'ServiceStack.Common, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL' not resolved
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'ServiceStack.Interfaces, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL' not resolved
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'ServiceStack.Text, Version=4.0.52.0, Culture=neutral, processorArchitecture=MSIL' not resolved
```

Errors:

/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp.sln (default targets) ->
(Build target) ->
/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp/ParadoxIp.csproj (default targets) ->
/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.targets (RestorePackages target) ->

```
/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 "/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.exe" install "/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp/packages.config" -source ""   -RequireConsent -solutionDir "/opt/paradoxapi/ParadoxAlarmControl-master/"' exited with code: 1.
```

/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp.sln (default targets) ->
(Build target) ->
/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel/Paradox.WebServices.ServiceModel.csproj (default targets) ->
/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.targets (RestorePackages target) ->

```
/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 "/opt/paradoxapi/ParadoxAlarmControl-master/.nuget/NuGet.exe" install "/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel/packages.config" -source ""   -RequireConsent -solutionDir "/opt/paradoxapi/ParadoxAlarmControl-master/"' exited with code: 1.
```

/opt/paradoxapi/ParadoxAlarmControl-master/ParadoxIp.sln (default targets) ->
(Build target) ->
/opt/paradoxapi/ParadoxAlarmControl-master/Paradox.WebServices.ServiceModel.SmartThings/Paradox.WebServices.ServiceModel.SmartThings.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

```
Request/SmartThingsSettingsRequest.cs(1,7): error CS0246: The type or namespace name `ServiceStack' could not be found. Are you missing an assembly reference?
Request/SmartThingsSettingsResetRequest.cs(1,7): error CS0246: The type or namespace name `ServiceStack' could not be found. Are you missing an assembly reference?
Request/SmartThingsStatusRequest.cs(2,7): error CS0246: The type or namespace name `ServiceStack' could not be found. Are you missing an assembly reference?
Request/StatusRequest.cs(2,7): error CS0246: The type or namespace name `ServiceStack' could not be found. Are you missing an assembly reference?
Request/SmartThingsStatusRequest.cs(8,45): error CS0246: The type or namespace name `IReturn' could not be found. Are you missing an assembly reference?
Request/StatusRequest.cs(8,34): error CS0246: The type or namespace name `IReturn' could not be found. Are you missing an assembly reference?

 4 Warning(s)
 8 Error(s)
```

Time Elapsed 00:00:28.0441310

**Comment by tracstarr** [comment]
I've not tried to build on linux directly. I'll try to find some time this weekend to take a look. I suspect that the manual install of selenium is not going to work. It expects the assemblies to be under the packages directory via nuget.

**Comment by tracstarr** [comment]
Added new file ParadoxIp.Build.msbuildproj for linux xbuilds. Just call xbuild ParadoxIp.Build.msbuildproj. It will restore nuget packages, copy the default app.config files and build the project.
